name: Integration Tests

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        api-level: [34]
    env:
      ANDROID_USER_HOME: /home/runner/.android
      ANDROID_EMULATOR_HOME: /home/runner/.android
      ANDROID_AVD_HOME: /home/runner/.android/avd
      AVD_CONFIG_PATH: "~/.android/avd/test.avd/config.ini"
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/free_up_space
      # https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: AVD cache
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: ~/.android/*
          key: avd-${{ matrix.api-level }}-integration_docker
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@d94c3fbe4fe6a29e4a5ba47c12fb47677c73656b
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          cores: 4
          ndk: 28.2.13676358
          force-avd-creation: false
          disk-size: 4096M
          ram-size: 4096M
          sdcard-path-or-size: 4096M
          emulator-options: -no-window -wipe-data -accel on -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: |
            cat ${{ env.AVD_CONFIG_PATH }}

            sed -i.bak 's/hw.lcd.density = .*/hw.lcd.density=420/' ${{ env.AVD_CONFIG_PATH }}
            sed -i.bak 's/hw.lcd.height = .*/hw.lcd.height=1920/' ${{ env.AVD_CONFIG_PATH }}
            sed -i.bak 's/hw.lcd.width = .*/hw.lcd.width=1080/' ${{ env.AVD_CONFIG_PATH }}

            if ! grep -q "hw.lcd.density"  ${{ env.AVD_CONFIG_PATH }} && echo "hw.lcd.density = 420" >>  ${{ env.AVD_CONFIG_PATH }}; then :; fi
            if ! grep -q "hw.lcd.height"  ${{ env.AVD_CONFIG_PATH }} && echo "hw.lcd.height = 1920" >>  ${{ env.AVD_CONFIG_PATH }}; then :; fi
            if ! grep -q "hw.lcd.width"  ${{ env.AVD_CONFIG_PATH }} && echo "hw.lcd.width = 1080" >>  ${{ env.AVD_CONFIG_PATH }}; then :; fi

            echo "Emulator settings (${{ env.AVD_CONFIG_PATH }})"
            cat ${{ env.AVD_CONFIG_PATH }}
            echo "Generated AVD snapshot for caching."
      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .tool_versions.yaml
          cache: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Gradle
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Prepare Homeserver
        run: ./scripts/prepare_integration_test.sh
      - name: Integration tests
        id: integration_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          cores: 16
          ndk: 28.2.13676358
          force-avd-creation: false
          disk-size: 4096M
          ram-size: 4096M
          sdcard-path-or-size: 4096M
          emulator-options: -no-snapshot-save -no-window -wipe-data -accel on -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: flutter test integration_test/mobile_test.dart
